### ISSUE TITLE
Any hope for "desktop" / core GLSL support?

### ISSUE THREAD

**Issue by metaleap** [WebGLTools/GL-Shader-Validator#5]
Hey, awesome utility... wondering if there's any chance of adding "GLSL core" support to the validator in some way? I know WebGL SL, ES SL and CSS SL are the hot topics these days but hey...

**Comment by paullewis** [comment]
Good idea! It entirely depends on whether ANGLE supports it. If it does then yeah, no probs. @brendankenny do you know?

**Comment by brendankenny** [comment]
No, unfortunately no desktop OpenGL support in ANGLE. This is a benefit from ANGLE's perspective, since OpenGL ES is considerably more streamlined, and it doesn't (yet) have a bunch of different versions, each adding new features that need support.

There has been talk about a more generalized OpenGL <-> DirectX translation library since the game industry needs it much more than they used to (OpenGL-like on consoles, mobile devices, etc), which could get us some of the validation. We could definitely add that in if or when it exists. We could also consider just starting up an OpenGL context in the background and try to compile the shader. This will be much slower than the ANGLE validation step, though, and you then expose the poor state of OpenGL drivers on many machines.

Even with those, however, it still won't be as nice as ANGLE. Since it needs to absorb the mess that is web content, it has incredibly robust validation (that keeps getting expanded as corner cases are found) and it gives you that nice line number in the error message, which the driver compiler often doesn't offer.

**Comment by metaleap** [comment]
Actually didn't realize the ANGLE-ness of this shader-validator sub-project before this thread. Yeah, of course, don't go there, not worth the hassle with the different versions & specs for desktop GL. I could certainly hack up a custom background shader compiler and wire it into Sublime Text one of these days, shouldn't take too long..
